<a href="https://colab.research.google.com/github/KODURISRIHARI/Numpy_Tutuorial/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#import numpy

In [87]:
import numpy as np

##check python and numpy version

In [89]:
import platform
print('Python version: ' + platform.python_version())
print('Numpy version: ' + np.__version__)

Python version: 3.11.11
Numpy version: 1.26.4


Numpy Data Types \
Numpy has the following data types:

int

float

complex

bool

string

unicode

object

The numeric data types have various precisions like 32-bit or 64-bit.

Numpy data types can be represented using either Type or Type Code

# *Numpy Data Types*

In [ ]:
dtypes = pd.DataFrame(
    {
        'Type': [
            'int8',
            'uint8',
            'int16',
            'uint16',
            'int or int32',
            'uint32',
            'int64',
            'uint64',
            'float16',
            'float32',
            'float or float64',
            'float128',
            'complex64',
            'complex or complex128',
            'bool',
            'object',
            'string_',
            'unicode_',
        ],

        'Type Code': [
            'i1',
            'u1',
            'i2',
            'u2',
            'i4 or i',
            'u4',
            'i8',
            'u8',
            'f2',
            'f4 or f',
            'f8 or d',
            'f16 or g',
            'c8',
            'c16',
            None,
            'O',
            'S',
            'U',
        ]
    }
)

In [ ]:
dtypes

Type Type Code
0                    int8        i1
1                   uint8        u1
2                   int16        i2
3                  uint16        u2
4            int or int32   i4 or i
5                  uint32        u4
6                   int64        i8
7                  uint64        u8
8                 float16        f2
9                 float32   f4 or f
10       float or float64   f8 or d
11               float128  f16 or g
12              complex64        c8
13  complex or complex128       c16
14                   bool      None
15                 object         O
16                string_         S
17               unicode_         U

Data types can be defined at creating the numpy array and converted to other types later.

You can use either type, type code or np dot methods to define the data type of an array, but when you use np dot method to define the data type, it can only follow type rather than type code.

In [ ]:
arr = np.array([1,2,3], dtype='f4')
arr.dtype

dtype('float32')

In [ ]:
# Identical to the above
arr = np.array([1,2,3], dtype='float32')
arr.dtype

dtype('float32')

In [ ]:
arr = np.array([1+2j, 3-4j], dtype=np.complex64)
arr.dtype

dtype('complex64')

In [ ]:
# Identical to the above
arr = np.array([1+2j, 3-4j], dtype='c8')
arr.dtype

dtype('complex64')

In [ ]:
# ERROR
arr = np.array([1+2j, 3-4j], dtype=np.c8)
arr.dtype

AttributeError: module 'numpy' has no attribute 'c8'

Type Conversion
astype method: convert the data type of an array to other data types.

Notice that astype returns a copy of the array instead of converting the data type in place. You need to assign the copy to the original array or a new array.

In [ ]:
arr = np.array([1,2,3], dtype='int16')
print('Original Data Type: ' + str(arr.dtype))

arr = arr.astype(np.float32)
print('Data Type After Conversion: ' + str(arr.dtype))

Original Data Type: int16
Data Type After Conversion: float32


WARNING: be cautious about data overflow when you downcast the data type (from higher precision to lower precision). Some unexpected and undefined values might occur and it is usually difficult to debug such issues.

In [ ]:
# An example of integer overflow at downcasting
arr = np.array([126,127,256], dtype='int16')
print('np array before type conversion: ' + str(arr))

# Range of int8 [-128, 127], 256 overflows after conversion
arr = arr.astype('int8')
print('np array after type conversion: ' + str(arr))

np array before type conversion: [126 127 256]
np array after type conversion: [126 127   0]


String and Unicode Data Type
The string_ and unicode_ data types are all implicitly fixed-length.

The length of the string is given by their type code appended with a number. For example, S3 represents string of length 3; U10 represents unicode of length 10. Otherwise, the default length is the length of the longest string in the array.

If the length of a string in the array is shorter than the length of the data type defined or converted to, the string will be truncated.

In [ ]:

# An example of truncated string
s = np.array(['abc', 'defg'], dtype='S3')
print(s)

# An example of truncated unicode
s = np.array(['abcd', 'efghi'], dtype='U3')
print(s)

[b'abc' b'def']
['abc' 'efg']


In [ ]:
arr = np.array(['a', 'ab', 'abc'], dtype=np.string_)
print('The array is ' + str(arr))
print('The data type is ' + str(arr.dtype) + ' because the longest string in the array is "abc" and its length is 3.')

arr = np.array(['a', 'abc', 'abcd'], dtype=np.unicode_)
print('The array is ' + str(arr))
print('The data type is ' + str(arr.dtype) + ' because the longest unicode in the array is "abcd" and its length is 4.')

The array is [b'a' b'ab' b'abc']
The data type is |S3 because the longest string in the array is "abc" and its length is 3.
The array is ['a' 'abc' 'abcd']
The data type is <U4 because the longest unicode in the array is "abcd" and its length is 4.


# create arrays

Create an array from an iterable
Such as

list

tuple

range iterator

Notice that not all iterables can be used to create a numpy array, such as set and dict

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Create an array with specified data type

In [ ]:
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)
print('Data Type: ' + str(arr.dtype))

[[1 2 3]
 [4 5 6]]
Data Type: int16


Create an aray within specified range \
np.arange() method can be used to replace np.array(range()) method

In [ ]:
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


Create an array of evenly spaced numbers within specified range
np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False) has 5
parameters:

start: start number (inclusive) \
stop: end number (inclusive unless endpoint set to False) \
num_of_elements: number of elements contained in the array \
endpoint: boolean value representing whether the stop number is inclusive or not \
retstep: boolean value representing whether to return the step size

In [ ]:
arr, step_size = np.linspace(0, 5, 8, endpoint=False, retstep=True)
print(arr)
print('The step size is ' + str(step_size))

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375]
The step size is 0.625


Create an array of random values of given shape
np.random.rand() method returns values in the range [0,1)

In [ ]:
arr = np.random.rand(3, 3)
print(arr)

[[0.88118799 0.694348   0.87219205]
 [0.88229357 0.57906044 0.83140587]
 [0.02211234 0.70500482 0.57218232]]


Create an array of zeros of given shape \

np.zeros(): create array of all zeros in given shape \
np.zeros_like(): create array of all zeros with the same shape and data type as the given input array

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape to a 2x3 array
reshaped_arr = np.reshape(arr, (2, 3),order='F')

print(reshaped_arr)  # Output: [[1 2 3]
                   #          [4 5 6]]

[[1 3 5]
 [2 4 6]]


In [ ]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.complex64)
zeros = np.zeros_like(arr)
print(zeros)
print('Data Type: ' + str(zeros.dtype))

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
Data Type: complex64



Create an array of ones of given shape

np.ones(): create array of all ones in given shape \
np.ones_like(): create array of all ones with the same shape and data type as the given input array

In [ ]:
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
arr = [[1,2,3], [4,5,6]]
ones = np.ones_like(arr)
print(ones)
print('Data Type: ' + str(ones.dtype))

[[1 1 1]
 [1 1 1]]
Data Type: int64


Create an empty array of given shape

np.empty(): create array of empty values in given shape

np.empty_like(): create array of empty values with the same shape and data type as the given input array

Notice that the initial values are not necessarily set to zeroes.

They are just some garbage values in random memory addresses.

In [ ]:
empty = np.empty((5,5))
print(empty)

[[ 4.00743058e-316  0.00000000e+000  1.24362093e-033  7.71867738e-304
  -2.01346939e-197]
 [-1.99439970e-114  9.82328242e-082  1.96956953e-208  8.97831878e-227
   1.64304299e-265]
 [-8.37524292e-114 -1.16615712e-230  1.41034535e-026  8.97509015e-171
   1.51976236e-091]
 [ 6.81487694e-106 -1.07546223e-172  3.68302919e-304  1.24425812e+268
   3.23611948e-188]
 [ 1.10081394e-289  9.06092918e-312  2.22507386e-307  1.95649823e-316
   6.93788656e-310]]


In [ ]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
empty = np.empty_like(arr)
print(empty)
print('Data Type: ' + str(empty.dtype))

[[1065353216 1073741824 1077936128]
 [1082130432 1084227584 1086324736]]
Data Type: int64


Create an array of constant values of given shape

np.full(): create array of constant values in given shape

np.full_like(): create array of constant values with the same shape and data type as the given input array

In [ ]:
full = np.full((4,4), 5)
print(full)


[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
arr = np.array([[1,2], [3,4]], dtype=np.float64)
full = np.full_like(arr, 5)
print(full)
print('Data Type: ' + str(full.dtype))

[[5. 5.]
 [5. 5.]]
Data Type: float64


Create an array in a repetitive manner \
np.repeat(iterable, reps, axis=None): repeat each element by n times \
iterable: input array \
reps: number of repetitions\
axis: which axis to repeat
along, default is None which will flatten the input array and then repeat
np.tile(): repeat the whole array by n times
iterable: input array
reps: number of repetitions, it can be a tuple to represent repetitions along x-axis and y-axis

In [ ]:
# No axis specified, then flatten the input array first and repeat
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3))

[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [ ]:
# An example of repeating along x-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=0))

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [ ]:
# An example of repeating along y-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=1))

[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]


In [ ]:
# Repeat the whole array by a specified number of times
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [ ]:
# Repeat along specified axes
print(np.tile(arr, (2,2)))

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


###Create an identity matrix of given size

np.eye(size, k=0): create an identity matrix of given size \
size: the size of the identity matrix \
k: the diagonal offset\
np.identity(): same as np.eye() but does not carry parameters

In [ ]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:

# An example of diagonal offset
identity_matrix = np.eye(5, k=-1)
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [ ]:

identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Create an array with given values on the diagonal


In [ ]:
arr = np.random.rand(5,5)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.39106592 0.353825   0.09099307 0.92465065 0.28040603]
 [0.26532197 0.41893426 0.85148129 0.13806684 0.37116812]
 [0.4594456  0.82279367 0.36026414 0.05825279 0.25613669]
 [0.87786486 0.12550069 0.69445054 0.36757315 0.56933979]
 [0.65778642 0.20595904 0.71285681 0.49282037 0.95949298]]
Values on the diagonal: [0.39106592 0.41893426 0.36026414 0.36757315 0.95949298]


In [ ]:
# Not necessarily to be a square matrix
arr = np.random.rand(10,3)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.13165709 0.43783742 0.87964397]
 [0.35180048 0.15918997 0.6635004 ]
 [0.28681795 0.59359901 0.22264161]
 [0.49594462 0.24085257 0.26764839]
 [0.30931607 0.44172183 0.43832435]
 [0.99572881 0.76206396 0.15561091]
 [0.56270279 0.24953673 0.79925299]
 [0.44504887 0.07542262 0.03403838]
 [0.35135974 0.80517607 0.42319845]
 [0.17429636 0.62140564 0.58156008]]
Values on the diagonal: [0.13165709 0.15918997 0.22264161]


In [ ]:
# Create a matrix given values on the diagonal
# All non-diagonal values set to zeros
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# Sampling Methods


In [90]:
np.random.seed(123)

set random state which is independent from the global seed


In [ ]:
rs = np.random.RandomState(321)
rs.rand(10)

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ])


generate a random sample from interval [0, 1) in a given shape

In [ ]:
# generate a random scalar
print(np.random.rand())

0.5699849330879277


In [ ]:
# generate a 1-D array
print(np.random.rand(3))

[0.0101435  0.02510073 0.21741478]


In [ ]:
# generate a 2-D array
print(np.random.rand(3,3))

[[0.75524275 0.03920224 0.18570446]
 [0.50721628 0.92080329 0.52894868]
 [0.95217287 0.49321175 0.04724005]]



generate a sample from the standard normal distribution (mean = 0, var = 1)

In [ ]:
print(np.random.randn(3,3))

[[ 1.33793709 -0.29277249 -0.3342595 ]
 [ 1.20744967  1.38838595 -0.67430609]
 [ 1.35899867 -0.26409987 -0.35140804]]


generate an array of random integers in a given interval [low, high)


In [ ]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i8'))

[2 4 7]


generate an array of random floating-point numbers in the interval [0.0, 1.0)


In [ ]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.78623564 0.12225665 0.62124533 0.69620687 0.44737251 0.8891414
 0.41439759 0.92380641 0.68998013 0.16117871]
[0.35153323 0.89134335 0.8319148  0.04258719 0.45332023 0.73815446
 0.25381082 0.8967563  0.46430358 0.43895692]
[0.78858326 0.39429354 0.44282151 0.35643505 0.46215881 0.99248193
 0.51356675 0.79853416 0.52550416 0.47092887]
[0.16726054 0.27636035 0.35540647 0.4254086  0.77120075 0.04435212
 0.02742692 0.02096286 0.33309364 0.18015601]


generate a random sample from a given 1-D array


In [ ]:

# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.8, 0.1]))

[1 1 0 1 2 1 1 1 1 1]


In [ ]:
print(np.random.choice(3, 10))

[2 1 0 2 1 2 1 1 2 0]


In [ ]:
print(np.random.choice([1,2,3], 10))

[2 2 2 1 2 2 3 1 1 2]


shuffle an array in place


In [ ]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
np.random.shuffle(arr)
print(arr)

[9 0 7 8 6 5 4 3 2 1]


generate a permutation of an array


In [ ]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [1 7 4 5 2 6 9 3 8 0]


#2. Inspect Arrays


In [ ]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)


In [ ]:

print(np.info(arr))

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x4ed14b0
byteorder:  little
byteswap:  False
type: int64
None


inspect the data type of an array


In [ ]:
print(arr.dtype)

int64


inspect the dimension of an array


In [ ]:
print(arr.shape)

(2, 3)


inspect the length of an array


In [ ]:
print(len(arr))

2


inspect the number of elements of an array


In [ ]:
print(arr.size)

6


inspect the no of bytes for every individual of an array


In [ ]:
print(arr.itemsize)

8


inspect the memory size of an array (in byte)


In [ ]:
print(arr.nbytes)

48


inspect the no of  dimensions an array (in byte)


In [ ]:
print(arr.ndim)

2


#. Math Functions

element-wise addition, subtraction, multiplication and division


In [108]:
arr = np.random.rand(5,5)
print(arr)

[[0.32295891 0.36178866 0.22826323 0.29371405 0.63097612]
 [0.09210494 0.43370117 0.43086276 0.4936851  0.42583029]
 [0.31226122 0.42635131 0.89338916 0.94416002 0.50183668]
 [0.62395295 0.1156184  0.31728548 0.41482621 0.86630916]
 [0.25045537 0.48303426 0.98555979 0.51948512 0.61289453]]


In [92]:
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[10.69646919 10.28613933 10.22685145 10.55131477 10.71946897]
 [10.42310646 10.9807642  10.68482974 10.4809319  10.39211752]
 [10.34317802 10.72904971 10.43857224 10.0596779  10.39804426]
 [10.73799541 10.18249173 10.17545176 10.53155137 10.53182759]
 [10.63440096 10.84943179 10.72445532 10.61102351 10.72244338]]
[[-9.30353081 -9.71386067 -9.77314855 -9.44868523 -9.28053103]
 [-9.57689354 -9.0192358  -9.31517026 -9.5190681  -9.60788248]
 [-9.65682198 -9.27095029 -9.56142776 -9.9403221  -9.60195574]
 [-9.26200459 -9.81750827 -9.82454824 -9.46844863 -9.46817241]
 [-9.36559904 -9.15056821 -9.27554468 -9.38897649 -9.27755662]]
[[6.96469186 2.86139335 2.26851454 5.51314769 7.1946897 ]
 [4.2310646  9.80764198 6.84829739 4.80931901 3.92117518]
 [3.43178016 7.29049707 4.38572245 0.59677897 3.98044255]
 [7.37995406 1.8249173  1.75451756 5.31551374 5.31827587]
 [6.34400959 8.49431794 7.24455325 6.11023511 7.22443383]]
[[0.06964692 0.02861393 0.02268515 0.05513148 0.0719469 ]
 [0.04231065 0.0980

In [93]:
arr1 = np.array([1,2,3])
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memoryarr = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[1 2 3]
[1 4 9]


###element-wise exponentiation


In [94]:
print(np.exp(arr))

[[2.00665506 1.33127794 1.25464348 1.73553334 2.05334253]
 [1.52669682 2.66649319 1.9834341  1.61758113 1.48011164]
 [1.40941964 2.07310961 1.55049191 1.06149458 1.48890992]
 [2.09173822 1.20020423 1.19178449 1.70157003 1.70204009]
 [1.88589208 2.33831783 2.0636068  1.84231606 2.05945911]]


###element-wise logorithm

In [95]:
# natural log
print(np.log(arr))

[[-0.36173173 -1.2512764  -1.48345987 -0.59544936 -0.32924188]
 [-0.86013145 -0.01942322 -0.37858503 -0.7320296  -0.93619369]
 [-1.06950597 -0.31601336 -0.82423073 -2.81879357 -0.92119209]
 [-0.30381768 -1.70105042 -1.74039117 -0.63195543 -0.63143593]
 [-0.4550741  -0.16318763 -0.32233518 -0.49261984 -0.32511623]]


In [96]:
# base 2
print(np.log2(arr))

[[-0.52186857 -1.80521026 -2.14018019 -0.85905184 -0.47499563]
 [-1.24090738 -0.02802178 -0.54618274 -1.05609547 -1.350642  ]
 [-1.54297096 -0.45591091 -1.18911358 -4.0666595  -1.32899925]
 [-0.43831626 -2.454097   -2.51085371 -0.91171896 -0.91096948]
 [-0.65653314 -0.23542999 -0.46503137 -0.7107002  -0.46904357]]


In [97]:
# base 10
print(np.log10(arr))

[[-0.15709809 -0.54342244 -0.64425843 -0.25860037 -0.14298793]
 [-0.37355034 -0.0084354  -0.16441739 -0.31791641 -0.40658375]
 [-0.46448054 -0.13724286 -0.35795886 -1.22418649 -0.40006864]
 [-0.13194634 -0.73875681 -0.75584228 -0.27445476 -0.27422914]
 [-0.19763617 -0.07087149 -0.13998839 -0.21394208 -0.14119618]]


###element-wise square root


In [98]:
print(np.sqrt(arr))

[[0.83454729 0.53491993 0.47628925 0.74250574 0.84821517]
 [0.65046634 0.9903354  0.8275444  0.69349254 0.62619288]
 [0.58581398 0.85384408 0.66224787 0.2442906  0.63090749]
 [0.85906659 0.42719051 0.41886962 0.7290757  0.7292651 ]
 [0.79649291 0.92164624 0.85114941 0.78167993 0.84996669]]


In [99]:
print(np.sin(arr))

[[0.64151316 0.28225064 0.22491076 0.52380765 0.65898535]
 [0.41059496 0.8309228  0.63254115 0.46260557 0.38214607]
 [0.33648149 0.6661612  0.42464727 0.05964248 0.38761624]
 [0.67280623 0.18148049 0.17455298 0.50687127 0.50710935]
 [0.59269514 0.75090528 0.66272766 0.57370608 0.66121965]]


In [100]:
print(np.cos(arr))

[[0.76711203 0.9593407  0.97437937 0.85183657 0.75215578]
 [0.91181785 0.55638772 0.77452676 0.8865642  0.92410193]
 [0.94169008 0.74580779 0.90535888 0.9982198  0.92182083]
 [0.73981875 0.98339455 0.98464778 0.86202176 0.86188172]
 [0.80542689 0.66040992 0.7488605  0.81906125 0.75019236]]


### sum along a specified axis

In [102]:
print(np.sum(arr,axis=0))

[2.83515003 3.02787677 2.25016052 2.23449945 2.76390171]


In [103]:
# sum along the column
print(np.sum(arr, axis=1))

[2.48024371 2.96174982 1.96852212 2.15931785 3.54175497]


### compute the min and max along a specified axis


In [104]:
print(np.min(arr, axis=0))

[0.34317802 0.18249173 0.17545176 0.0596779  0.39211752]


In [105]:
print(np.max(arr, axis=1))

[0.71946897 0.9807642  0.72904971 0.73799541 0.84943179]


In [106]:
print(np.max(arr))
print(np.min(arr))

0.9807641983846155
0.05967789660956835


###compute the indices of the min and max along a specified axis


In [107]:
# along the row
print(np.argmin(arr, axis=0))
print(np.argmax(arr, axis=0))

[2 3 3 2 1]
[3 1 4 4 4]


In [109]:
# along the column
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))

[2 0 0 1 0]
[4 3 3 4 2]


In [110]:
# if axis not specified, return the index of the flattened array
print(np.argmin(arr))
print(np.argmax(arr))

5
22


###compute element-wise min and max of two arrays

In [111]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


###split fractional and integral parts of a floating-point array


In [112]:
arr1 = np.random.rand(10) * 10
re, intg = np.modf(arr1)
print('fractional: ', re)
print('integral: ', intg)

fractional:  [0.20628666 0.26340801 0.03060128 0.45068006 0.42763834 0.04120789
 0.17022211 0.81300766 0.75456842 0.10422337]
integral:  [1. 8. 6. 5. 3. 3. 4. 6. 8. 5.]


### compute the mean

In [113]:
# compute the overall mean
print(np.mean(arr))

0.4792521952184076


In [114]:
# compute the mean along the row
print(np.mean(arr, axis=0))

[0.32034668 0.36409876 0.57107208 0.5331741  0.60756935]


In [115]:
# compute the mean along the column
print(np.mean(arr, axis=1))

[0.36754019 0.37523685 0.61559968 0.46759844 0.57028581]


### compute the median

In [116]:
# compute the overall median
print(np.median(arr))

0.4308627633296438


In [117]:
# compute the median along the row
print(np.median(arr, axis=0))

[0.31226122 0.42635131 0.43086276 0.4936851  0.61289453]


In [118]:
# compute the median along the column
print(np.median(arr, axis=1))

[0.32295891 0.43086276 0.50183668 0.41482621 0.51948512]


###compute the percentile


In [119]:
arr1 = np.random.rand(100)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [5, 65, 95]))

[0.08300353 0.6650086  0.92525508]


###compute the standard deviation & variance


In [120]:
# compute the overall standard deviation
print(np.std(arr))

0.2363407440309854


In [121]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

[0.17275882 0.13008717 0.30895714 0.22000161 0.14948646]


In [122]:
# compute the standard deviation along the column
print(np.std(arr, axis=1))

[0.13875693 0.14371199 0.25529986 0.25794799 0.23947987]


In [123]:
# compute the overall variance
print(np.var(arr))

0.05585694728911976


In [124]:
# compute the variance along the row
print(np.var(arr, axis=0))

[0.02984561 0.01692267 0.09545451 0.04840071 0.0223462 ]


In [125]:
# compute the variance along the column
print(np.var(arr, axis=1))

[0.01925349 0.02065314 0.06517802 0.06653716 0.05735061]


###compute the covariance & correlation


In [132]:
# Generate a 5x5 matrix with random values between 5 and 50
arr = np.random.randint(5, 51, size=(5, 5))

# Print the array
print(arr)

[[23 37 35  8 36]
 [46 32 20 47 32]
 [19 26 35 25 36]
 [11 37 12 18 29]
 [36 32  6 21 31]]


In [133]:
print(np.cov(arr))

[[ 154.7  -112.65   50.05   63.85    0.8 ]
 [-112.65  126.8   -64.6   -20.95   79.65]
 [  50.05  -64.6    51.7    16.9   -46.55]
 [  63.85  -20.95   16.9   127.3    58.15]
 [   0.8    79.65  -46.55   58.15  145.7 ]]


In [134]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[ 1.         -0.20487944]
 [-0.20487944  1.        ]]


### compute cumulative sum & product

In [135]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0))

[[ 23  37  35   8  36]
 [ 69  69  55  55  68]
 [ 88  95  90  80 104]
 [ 99 132 102  98 133]
 [135 164 108 119 164]]


In [136]:
# calculate the cumulative sums along the column
print(np.cumsum(arr, axis=1))

[[ 23  60  95 103 139]
 [ 46  78  98 145 177]
 [ 19  45  80 105 141]
 [ 11  48  60  78 107]
 [ 36  68  74  95 126]]


In [137]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0))

[[      23       37       35        8       36]
 [    1058     1184      700      376     1152]
 [   20102    30784    24500     9400    41472]
 [  221122  1139008   294000   169200  1202688]
 [ 7960392 36448256  1764000  3553200 37283328]]


In [139]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1))

[[      23      851    29785   238280  8578080]
 [      46     1472    29440  1383680 44277760]
 [      19      494    17290   432250 15561000]
 [      11      407     4884    87912  2549448]
 [      36     1152     6912   145152  4499712]]


###element-wise comparison

In [153]:
arr1 = np.arange(1,6)
arr2 = np.arange(2,12,2)
print(arr1)
print(arr2)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [154]:
# return an array of bools
print(arr1 == arr2)
print(arr1 < 3)


[False False False False False]
[ True  True False False False]


# *Linear algebra*

In [77]:
arr1 = np.random.rand(5,5)
arr2 = np.random.rand(5,5)

###matrix multiplication

In [78]:
print(arr1.dot(arr2))
# or
print("\n")
print(np.dot(arr1, arr2))
# or
print("\n")
print(arr1 @ arr2)

[[0.94947524 0.43465217 1.04235987 1.60172599 0.85755955]
 [1.33763084 0.79342586 1.38610424 2.12088416 1.39568631]
 [1.93971156 0.8411649  2.21084153 2.43512351 1.32432791]
 [1.11298316 0.27102013 1.41559575 1.26736668 0.50712777]
 [1.71339824 0.62632397 1.36500312 2.24965183 1.45423638]]


[[0.94947524 0.43465217 1.04235987 1.60172599 0.85755955]
 [1.33763084 0.79342586 1.38610424 2.12088416 1.39568631]
 [1.93971156 0.8411649  2.21084153 2.43512351 1.32432791]
 [1.11298316 0.27102013 1.41559575 1.26736668 0.50712777]
 [1.71339824 0.62632397 1.36500312 2.24965183 1.45423638]]


[[0.94947524 0.43465217 1.04235987 1.60172599 0.85755955]
 [1.33763084 0.79342586 1.38610424 2.12088416 1.39568631]
 [1.93971156 0.8411649  2.21084153 2.43512351 1.32432791]
 [1.11298316 0.27102013 1.41559575 1.26736668 0.50712777]
 [1.71339824 0.62632397 1.36500312 2.24965183 1.45423638]]


###QR factorization


In [73]:
arr = np.random.rand(5,5)
q, r = np.linalg.qr(arr)
print(q,"\n")
print(r)

[[-0.75338261  0.50064451  0.19696348  0.35110902  0.14034798]
 [-0.1876773  -0.66413404  0.41252954  0.46231415 -0.37388262]
 [-0.43124003 -0.07086705 -0.60789963 -0.23556047 -0.61966056]
 [-0.38186097 -0.25407884  0.42427311 -0.76240223  0.16840818]
 [-0.25574618 -0.48857226 -0.49140119  0.16199442  0.65434984]] 

[[-0.97072249 -1.70734588 -1.29610876 -1.55114034 -1.54299354]
 [ 0.         -0.63668285 -1.2097192  -0.35896987 -0.22524927]
 [ 0.          0.         -0.13839977  0.02070195  0.15828929]
 [ 0.          0.          0.         -0.38507152 -0.3401064 ]
 [ 0.          0.          0.          0.         -0.22892095]]


###singular value decomposition (SVD)


In [74]:
arr = np.random.rand(5,5)

u, s, v = np.linalg.svd(arr)
print(u)
print(s)
print(v)

[[-0.56051161  0.42170615 -0.2871973  -0.29398803 -0.58230525]
 [-0.54398252 -0.06521528  0.57929178 -0.44017425  0.4129136 ]
 [-0.27825573 -0.23780893  0.51514734  0.6164693  -0.46969083]
 [-0.32280536 -0.82382985 -0.45640153 -0.09275624 -0.01396424]
 [-0.45637726  0.28751031 -0.32902827  0.57548201  0.51924798]]
[2.81726349e+00 6.51223228e-01 5.28188617e-01 2.81395478e-01
 1.07921413e-03]
[[-0.52470438 -0.40996963 -0.53276713 -0.17415914 -0.49237992]
 [-0.22692175  0.12600148  0.73296373 -0.31254425 -0.54562845]
 [ 0.24886837 -0.85269677  0.28244578 -0.27454374  0.23626862]
 [-0.45785312 -0.25953296  0.30759092  0.78727656  0.0927179 ]
 [-0.63374039  0.14696728  0.0673465  -0.42048311  0.62883395]]


###compute eigen values


In [75]:
arr = np.random.rand(5,5)
print(np.linalg.eigvals(arr))

[ 2.79324019+0.j          0.25069791+0.26740775j  0.25069791-0.26740775j
 -0.2152348 +0.30526548j -0.2152348 -0.30526548j]


###eigen value decomposition


In [76]:
arr = np.random.rand(5,5)

w, v = np.linalg.eig(arr)
print(w)    # eigen values
print(v)    # eigen vectors

[ 2.72228306+0.j          0.48174907+0.j          0.04551495+0.27179108j
  0.04551495-0.27179108j -0.23589797+0.j        ]
[[ 0.49889058+0.j          0.09129305+0.j         -0.54536196+0.16686421j
  -0.54536196-0.16686421j  0.53367382+0.j        ]
 [ 0.40090643+0.j          0.66137586+0.j          0.69525218+0.j
   0.69525218-0.j         -0.47817078+0.j        ]
 [ 0.28150506+0.j         -0.7340859 +0.j         -0.20570547+0.19002133j
  -0.20570547-0.19002133j -0.01215494+0.j        ]
 [ 0.55540104+0.j          0.09270604+0.j         -0.15319126-0.1334533j
  -0.15319126+0.1334533j  -0.45346722+0.j        ]
 [ 0.45018531+0.j         -0.0822863 +0.j         -0.1067153 -0.24550506j
  -0.1067153 +0.24550506j  0.52987234+0.j        ]]


###compute the trace & determinant


In [80]:
# notice this is not a function in linalg!!!
print(np.trace(arr))

3.0591640619938465


In [81]:
print(np.linalg.det(arr))

-0.023494186676471573


###calculate the inverse/psedo-inverse of a matrix

In [83]:
arr = np.random.rand(5,5)

In [84]:
# compute the inverse of a matrix
print(np.linalg.inv(arr))

[[-10.1003745   -2.73726227   3.1408319   18.5392584  -18.61525974]
 [ 17.49103332   6.62545038  -5.36245855 -33.26412207  32.64235549]
 [ -6.61171884  -3.99786069   3.58407899  12.78142812 -12.94607754]
 [ -8.59107102  -3.01132103   2.22436482  15.47544522 -12.12797211]
 [ 12.33233604   4.69786756  -3.92531219 -20.19485149  17.03080663]]


In [85]:
# compute the psudo-inverse of a matrix
print(np.linalg.pinv(arr))

[[-10.1003745   -2.73726227   3.1408319   18.5392584  -18.61525974]
 [ 17.49103332   6.62545038  -5.36245855 -33.26412207  32.64235549]
 [ -6.61171884  -3.99786069   3.58407899  12.78142812 -12.94607754]
 [ -8.59107102  -3.01132103   2.22436482  15.47544522 -12.12797211]
 [ 12.33233604   4.69786756  -3.92531219 -20.19485149  17.03080663]]


###solve a linear system


In [ ]:
# solve a linear system in closed form
y = [1,2,3,4,5]
print(np.linalg.solve(arr, y))

In [ ]:
# calculate the least-squares solution of a linear system
y = [1,2,3,4,5]
solution, residuals, rank, singular = np.linalg.lstsq(arr, y)
print(solution)
print("\n")
print(residuals)
print("\n")
print(rank)
print("\n")
print(singular)

In [ ]:
import numpy as np
import pandas as pd

# Generate a 5X5 array with random values between 0 and 1
random_array = np.random.rand(5,5)

#print the randomly generated array of 5X5
print(random_array)

[[0.77371818 0.44681798 0.56800486 0.50758521 0.70377188]
 [0.22898165 0.78228296 0.62380097 0.21816765 0.00363411]
 [0.48819417 0.71459797 0.5670589  0.87969213 0.95316507]
 [0.29173823 0.97524602 0.81151215 0.07834766 0.16833197]
 [0.80733647 0.69112643 0.42938061 0.56166331 0.8359976 ]]


In [ ]:
# Generate a 5X5 array with random values between 0 and 1 with index from 2 to 11 and columns from list consisting Names
df = pd.DataFrame(random_array,index=range(2,11,2),columns=list('ABCDE'))

#print the data frame
df


A         B         C         D         E
2   0.773718  0.446818  0.568005  0.507585  0.703772
4   0.228982  0.782283  0.623801  0.218168  0.003634
6   0.488194  0.714598  0.567059  0.879692  0.953165
8   0.291738  0.975246  0.811512  0.078348  0.168332
10  0.807336  0.691126  0.429381  0.561663  0.835998

In [ ]:
# Reshape the array into a single dimension
flattened_array = random_array.reshape(-1)

# Print the flattened array
print(flattened_array)


[0.77371818 0.44681798 0.56800486 0.50758521 0.70377188 0.22898165
 0.78228296 0.62380097 0.21816765 0.00363411 0.48819417 0.71459797
 0.5670589  0.87969213 0.95316507 0.29173823 0.97524602 0.81151215
 0.07834766 0.16833197 0.80733647 0.69112643 0.42938061 0.56166331
 0.8359976 ]


In [ ]:
# Reshape the flattened array back to 5X5
to_original_shape = flattened_array.reshape(5,5)

## Generate a 5X5 array with random values between 0 and 1 with index from 1 to 10 and columns from list consisting Names
df = pd.DataFrame(to_original_shape,index=range(1,11,2),columns=tuple('EDCBA'))

# print the dataframe
df


E         D         C         B         A
1  0.773718  0.446818  0.568005  0.507585  0.703772
3  0.228982  0.782283  0.623801  0.218168  0.003634
5  0.488194  0.714598  0.567059  0.879692  0.953165
7  0.291738  0.975246  0.811512  0.078348  0.168332
9  0.807336  0.691126  0.429381  0.561663  0.835998

In [ ]:
# Flatten the array into a single dimension
flattened_array = random_array.flatten()

# Print the flattened array
print(flattened_array)

[0.77371818 0.44681798 0.56800486 0.50758521 0.70377188 0.22898165
 0.78228296 0.62380097 0.21816765 0.00363411 0.48819417 0.71459797
 0.5670589  0.87969213 0.95316507 0.29173823 0.97524602 0.81151215
 0.07834766 0.16833197 0.80733647 0.69112643 0.42938061 0.56166331
 0.8359976 ]


In [61]:
df.to_csv('data.txt', sep=',', index=False)

In [62]:
df = pd.read_csv('data.txt', sep=',')
df.head(2)

StudentID            Name  Age  Gender Grade     Score1     Score2  \
0          1     Sai Krishna   19    Male     A  74.063471  56.116235   
1          2  Alexander Gole   20  Female     C  58.954435  70.733649   

      Score3      City                               Address  
0  77.640514  Bhatpara   H.No. 43 Khatri Road, Phusro 451991  
1  82.537707      Pune  91/932, Grewal Marg, Panihati-051424

**Import io:** The io module is used to create an in-memory file-like object from your string data.

**Create StringIO object:** A StringIO object is created from your data string, which acts like a file that Pandas can read from.

**Use pd.read_csv:** This function is used to read the comma-separated values from the StringIO object and create the DataFrame. The sep=',' argument specifies that the values are separated by commas.

**Set Column Names:** The columns= argument is used to define the column names for your DataFrame. You need to provide the correct column names here

In [60]:
import pandas as pd
import io

data = """
1,Sai Krishna,19,Male,A,74.06347136834738,56.116235231528634,77.64051430437854,Bhatpara,"H.No. 43 Khatri Road, Phusro 451991"
2,Alexander Gole,20,Female,C,58.95443455101223,70.73364902517254,82.5377067826966,Pune,"91/932, Grewal Marg, Panihati-051424"
3,Vinaya Naik,24,Female,B,77.8707658127084,58.04904175285642,65.3944009010486,Gopalpur,"90 Gupta Circle, Pimpri-Chinchwad 957824"
4,Dalaja Majumdar,18,Female,B,74.90256098471947,69.36454622409912,68.25419582360608,Thoothukudi,65/663 Kant Road Adoni-883437
5,Aarush Devi,20,Male,C,71.62871626948419,89.0563685404112,57.58425210823947,Arrah,34/999 Lad Ganj Jabalpur-863881
6,Sachi Korpal,22,Female,D,70.19746422177616,69.15077260198619,69.79500605847586,Bihar Sharif,"83 Ravel Chowk, Kirari Suleman Nagar-719890"
7,Avi Chaudry,22,Male,B,68.64355271271772,79.83232719217446,60.435393759724505,Korba,"97, Krishnamurthy Nagar, Dharmavaram 334131"
8,Quincy Tiwari,24,Male,A,63.45646434053456,62.44801210596499,64.12819499417748,Karawal Nagar,"98/627, Batra Circle, Nizamabad-935273"
9,Vasudha Kale,22,Male,B,70.58933130100976,62.644493588577376,67.38152126065323,Bidar,"29, Ganesh Chowk, Mumbai-302116"
10,Sai Babu,23,Female,B,73.30005142520044,65.03219230403133,74.14455942350338,Nellore,"28/391, Sabharwal Street Vijayawada 410182"
91,Aashi Yadav,22,Male,C,61.35669039241904,56.35609655578436,71.06873025087224,Bardhaman,95/86 Saraf Bhusawal 464547
92,Sanya Bandi,23,Female,B,67.79538446056391,67.47728041242361,70.62915252043548,Avadi,"87/14 Chand Circle, Orai-559650"
93,Irya Handa,19,Female,D,86.51710864645341,66.98854077502686,79.07856266463612,Aligarh,"46/17, Nagar Nagar Nagpur-571963"
94,Anthony Bhatti,21,Male,C,51.2749223156523,58.612304136438496,70.68943456505589,Secunderabad,"02, Datta Ganj, Jalna-465157"
95,Pranit Nigam,23,Female,A,92.82479180093895,65.33441772489351,80.21164632343056,Vellore,"H.No. 624 Mutti Circle, Saharsa-227531"
96,Manan Mital,22,Female,C,81.03689363558578,76.13493312954682,65.63485012740111,Tiruchirappalli,"H.No. 32, Lad Chowk Bulandshahr 914574"
97,Hardik Gade,18,Female,B,89.3525097754823,76.59182963625865,68.67302353876009,Ludhiana,"71, Sachar Circle Gorakhpur-045411"
98,Rachit Issac,20,Male,B,75.42343891622843,81.05966191153823,67.23970298983096,Secunderabad,H.No. 520 Murthy Path Tiruvottiyur 643087
99,Zansi Pau,20,Female,C,77.95367656330035,72.8010740298686,59.05305107465219,Firozabad,"86/90, Sabharwal Road, Davanagere 078087"
100,Manan Khalsa,22,Female,D,59.901210433276006,77.35389546309241,69.28655531076302,Tiruppur,28/078 Sankar Zila Phagwara-265756
"""
column_names = ["StudentID", "Name", "Age", "Gender", "Grade", "Score1", "Score2", "Score3", "City", "Address"]

data_io = io.StringIO(data)

df = pd.read_csv(data_io, sep=',', header=None, names=column_names)
df.head()

StudentID             Name  Age  Gender Grade     Score1     Score2  \
0          1      Sai Krishna   19    Male     A  74.063471  56.116235   
1          2   Alexander Gole   20  Female     C  58.954435  70.733649   
2          3      Vinaya Naik   24  Female     B  77.870766  58.049042   
3          4  Dalaja Majumdar   18  Female     B  74.902561  69.364546   
4          5      Aarush Devi   20    Male     C  71.628716  89.056369   

      Score3         City                                   Address  
0  77.640514     Bhatpara       H.No. 43 Khatri Road, Phusro 451991  
1  82.537707         Pune      91/932, Grewal Marg, Panihati-051424  
2  65.394401     Gopalpur  90 Gupta Circle, Pimpri-Chinchwad 957824  
3  68.254196  Thoothukudi             65/663 Kant Road Adoni-883437  
4  57.584252        Arrah           34/999 Lad Ganj Jabalpur-863881

In [ ]:
!pip install faker[india]

## ***generating data using numpy for random generation , with pandas for creating  dataset  [ dataframe ]  and generating random name with faker library***

In [ ]:
import numpy as np
import pandas as pd
from faker import Faker

# Initialize Faker for name generation
fake = Faker('en_IN')  # Specify 'en_IN' for Indian English

# Define number of records
num_records = 300

# Generate random data using NumPy
student_id = np.arange(1, num_records + 1)  # Student IDs
age = np.random.randint(18, 25, size=num_records)  # Age between 18 and 24
gender = np.random.choice(['Male', 'Female'], size=num_records)  # Gender
grade = np.random.choice(['A', 'B', 'C', 'D', 'F'], size=num_records, p=[0.2, 0.3, 0.3, 0.15, 0.05])  # Grades with probabilities
score1 = np.random.randn(num_records) * 10 + 70  # Score 1 (normal distribution)
score2 = np.random.randn(num_records) * 10 + 70  # Score 2 (normal distribution)
score3 = np.random.randn(num_records) * 10 + 70  # Score 3 (normal distribution)

# Generate Indian names using Faker
names = [fake.name() for _ in range(num_records)]

# Generate Indian cities using Faker
city = [fake.city() for _ in range(num_records)]

# Generate Indian addresses using Faker
address = [fake.address().replace('\n', ' ') for _ in range(num_records)]

# Create a Pandas DataFrame
df = pd.DataFrame({
    'StudentID': student_id,
    'Name': names,
    'Age': age,
    'Gender': gender,
    'Grade': grade,
    'Score1': score1,
    'Score2': score2,
    'Score3': score3,
    'City': city,
    'Address': address
})

# Print the DataFrame
df.head()

StudentID             Name  Age  Gender Grade     Score1     Score2  \
0          1      Sai Krishna   19    Male     A  74.063471  56.116235   
1          2   Alexander Gole   20  Female     C  58.954435  70.733649   
2          3      Vinaya Naik   24  Female     B  77.870766  58.049042   
3          4  Dalaja Majumdar   18  Female     B  74.902561  69.364546   
4          5      Aarush Devi   20    Male     C  71.628716  89.056369   

      Score3         City                                   Address  
0  77.640514     Bhatpara       H.No. 43 Khatri Road, Phusro 451991  
1  82.537707         Pune      91/932, Grewal Marg, Panihati-051424  
2  65.394401     Gopalpur  90 Gupta Circle, Pimpri-Chinchwad 957824  
3  68.254196  Thoothukudi             65/663 Kant Road Adoni-883437  
4  57.584252        Arrah           34/999 Lad Ganj Jabalpur-863881