<a href="https://colab.research.google.com/github/KODURISRIHARI/Numpy_Tutuorial/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

Numpy Data Types \
Numpy has the following data types:

int

float

complex

bool

string

unicode

object

The numeric data types have various precisions like 32-bit or 64-bit.

Numpy data types can be represented using either Type or Type Code

In [ ]:
dtypes = pd.DataFrame(
    {
        'Type': [
            'int8',
            'uint8',
            'int16',
            'uint16',
            'int or int32',
            'uint32',
            'int64',
            'uint64',
            'float16',
            'float32',
            'float or float64',
            'float128',
            'complex64',
            'complex or complex128',
            'bool',
            'object',
            'string_',
            'unicode_',
        ],

        'Type Code': [
            'i1',
            'u1',
            'i2',
            'u2',
            'i4 or i',
            'u4',
            'i8',
            'u8',
            'f2',
            'f4 or f',
            'f8 or d',
            'f16 or g',
            'c8',
            'c16',
            None,
            'O',
            'S',
            'U',
        ]
    }
)

In [ ]:
dtypes

Type Type Code
0                    int8        i1
1                   uint8        u1
2                   int16        i2
3                  uint16        u2
4            int or int32   i4 or i
5                  uint32        u4
6                   int64        i8
7                  uint64        u8
8                 float16        f2
9                 float32   f4 or f
10       float or float64   f8 or d
11               float128  f16 or g
12              complex64        c8
13  complex or complex128       c16
14                   bool      None
15                 object         O
16                string_         S
17               unicode_         U

Data types can be defined at creating the numpy array and converted to other types later.

You can use either type, type code or np dot methods to define the data type of an array, but when you use np dot method to define the data type, it can only follow type rather than type code.

In [ ]:
arr = np.array([1,2,3], dtype='f4')
arr.dtype

dtype('float32')

In [ ]:
# Identical to the above
arr = np.array([1,2,3], dtype='float32')
arr.dtype

dtype('float32')

In [ ]:
arr = np.array([1+2j, 3-4j], dtype=np.complex64)
arr.dtype

dtype('complex64')

In [ ]:
# Identical to the above
arr = np.array([1+2j, 3-4j], dtype='c8')
arr.dtype

dtype('complex64')

In [ ]:
# ERROR
arr = np.array([1+2j, 3-4j], dtype=np.c8)
arr.dtype

AttributeError: module 'numpy' has no attribute 'c8'

Type Conversion
astype method: convert the data type of an array to other data types.

Notice that astype returns a copy of the array instead of converting the data type in place. You need to assign the copy to the original array or a new array.

In [ ]:
arr = np.array([1,2,3], dtype='int16')
print('Original Data Type: ' + str(arr.dtype))

arr = arr.astype(np.float32)
print('Data Type After Conversion: ' + str(arr.dtype))

Original Data Type: int16
Data Type After Conversion: float32


WARNING: be cautious about data overflow when you downcast the data type (from higher precision to lower precision). Some unexpected and undefined values might occur and it is usually difficult to debug such issues.

In [ ]:
# An example of integer overflow at downcasting
arr = np.array([126,127,256], dtype='int16')
print('np array before type conversion: ' + str(arr))

# Range of int8 [-128, 127], 256 overflows after conversion
arr = arr.astype('int8')
print('np array after type conversion: ' + str(arr))

np array before type conversion: [126 127 256]
np array after type conversion: [126 127   0]


String and Unicode Data Type
The string_ and unicode_ data types are all implicitly fixed-length.

The length of the string is given by their type code appended with a number. For example, S3 represents string of length 3; U10 represents unicode of length 10. Otherwise, the default length is the length of the longest string in the array.

If the length of a string in the array is shorter than the length of the data type defined or converted to, the string will be truncated.

In [ ]:

# An example of truncated string
s = np.array(['abc', 'defg'], dtype='S3')
print(s)

# An example of truncated unicode
s = np.array(['abcd', 'efghi'], dtype='U3')
print(s)

[b'abc' b'def']
['abc' 'efg']


In [ ]:
arr = np.array(['a', 'ab', 'abc'], dtype=np.string_)
print('The array is ' + str(arr))
print('The data type is ' + str(arr.dtype) + ' because the longest string in the array is "abc" and its length is 3.')

arr = np.array(['a', 'abc', 'abcd'], dtype=np.unicode_)
print('The array is ' + str(arr))
print('The data type is ' + str(arr.dtype) + ' because the longest unicode in the array is "abcd" and its length is 4.')

The array is [b'a' b'ab' b'abc']
The data type is |S3 because the longest string in the array is "abc" and its length is 3.
The array is ['a' 'abc' 'abcd']
The data type is <U4 because the longest unicode in the array is "abcd" and its length is 4.


Create an array from an iterable
Such as

list

tuple

range iterator

Notice that not all iterables can be used to create a numpy array, such as set and dict

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Create an array with specified data type

In [ ]:
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)
print('Data Type: ' + str(arr.dtype))

[[1 2 3]
 [4 5 6]]
Data Type: int16


Create an aray within specified range \
np.arange() method can be used to replace np.array(range()) method

In [ ]:
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


Create an array of evenly spaced numbers within specified range
np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False) has 5
parameters:

start: start number (inclusive) \
stop: end number (inclusive unless endpoint set to False) \
num_of_elements: number of elements contained in the array \
endpoint: boolean value representing whether the stop number is inclusive or not \
retstep: boolean value representing whether to return the step size

In [ ]:
arr, step_size = np.linspace(0, 5, 8, endpoint=False, retstep=True)
print(arr)
print('The step size is ' + str(step_size))

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375]
The step size is 0.625


Create an array of random values of given shape
np.random.rand() method returns values in the range [0,1)

In [ ]:
arr = np.random.rand(3, 3)
print(arr)

[[0.88118799 0.694348   0.87219205]
 [0.88229357 0.57906044 0.83140587]
 [0.02211234 0.70500482 0.57218232]]


Create an array of zeros of given shape \

np.zeros(): create array of all zeros in given shape \
np.zeros_like(): create array of all zeros with the same shape and data type as the given input array

In [29]:
import numpy as np
import pandas as pd

# Generate a 5X5 array with random values between 0 and 1
random_array = np.random.rand(5,5)

#print the randomly generated array of 5X5
print(random_array)

[[0.94997842 0.86526444 0.68841642 0.98015932 0.62550575]
 [0.9139665  0.8244655  0.45360428 0.42603491 0.78621239]
 [0.21631082 0.25397593 0.80054287 0.32895958 0.516694  ]
 [0.54455894 0.60214757 0.54748836 0.46250365 0.3727329 ]
 [0.7567476  0.87662343 0.09422193 0.75049821 0.34010073]]


In [30]:
# Generate a 5X5 array with random values between 0 and 1 with index from 2 to 11 and columns from list consisting Names
df = pd.DataFrame(random_array,index=range(2,11,2),columns=list('ABCDE'))

#print the data frame
df

A         B         C         D         E
2   0.949978  0.865264  0.688416  0.980159  0.625506
4   0.913966  0.824465  0.453604  0.426035  0.786212
6   0.216311  0.253976  0.800543  0.328960  0.516694
8   0.544559  0.602148  0.547488  0.462504  0.372733
10  0.756748  0.876623  0.094222  0.750498  0.340101

In [31]:
# Reshape the array into a single dimension
flattened_array = random_array.reshape(-1)

# Print the flattened array
print(flattened_array)

[0.94997842 0.86526444 0.68841642 0.98015932 0.62550575 0.9139665
 0.8244655  0.45360428 0.42603491 0.78621239 0.21631082 0.25397593
 0.80054287 0.32895958 0.516694   0.54455894 0.60214757 0.54748836
 0.46250365 0.3727329  0.7567476  0.87662343 0.09422193 0.75049821
 0.34010073]


In [32]:
# Reshape the flattened array back to 5X5
to_original_shape = flattened_array.reshape(5,5)

## Generate a 5X5 array with random values between 0 and 1 with index from 1 to 10 and columns from list consisting Names
df = pd.DataFrame(to_original_shape,index=range(1,11,2),columns=tuple('EDCBA'))

# print the dataframe
df

E         D         C         B         A
1  0.949978  0.865264  0.688416  0.980159  0.625506
3  0.913966  0.824465  0.453604  0.426035  0.786212
5  0.216311  0.253976  0.800543  0.328960  0.516694
7  0.544559  0.602148  0.547488  0.462504  0.372733
9  0.756748  0.876623  0.094222  0.750498  0.340101

In [33]:
# Flatten the array into a single dimension
flattened_array = random_array.flatten()

# Print the flattened array
print(flattened_array)

[0.94997842 0.86526444 0.68841642 0.98015932 0.62550575 0.9139665
 0.8244655  0.45360428 0.42603491 0.78621239 0.21631082 0.25397593
 0.80054287 0.32895958 0.516694   0.54455894 0.60214757 0.54748836
 0.46250365 0.3727329  0.7567476  0.87662343 0.09422193 0.75049821
 0.34010073]


In [37]:
!pip install faker[india]

In [38]:
import numpy as np
import pandas as pd
from faker import Faker

# Initialize Faker for name generation
fake = Faker('en_IN')  # Specify 'en_IN' for Indian English

# Define number of records
num_records = 300

# Generate random data using NumPy
student_id = np.arange(1, num_records + 1)  # Student IDs
age = np.random.randint(18, 25, size=num_records)  # Age between 18 and 24
gender = np.random.choice(['Male', 'Female'], size=num_records)  # Gender
grade = np.random.choice(['A', 'B', 'C', 'D', 'F'], size=num_records, p=[0.2, 0.3, 0.3, 0.15, 0.05])  # Grades with probabilities
score1 = np.random.randn(num_records) * 10 + 70  # Score 1 (normal distribution)
score2 = np.random.randn(num_records) * 10 + 70  # Score 2 (normal distribution)
score3 = np.random.randn(num_records) * 10 + 70  # Score 3 (normal distribution)

# Generate Indian names using Faker
names = [fake.name() for _ in range(num_records)]

# Generate Indian cities using Faker
city = [fake.city() for _ in range(num_records)]

# Generate Indian addresses using Faker
address = [fake.address().replace('\n', ' ') for _ in range(num_records)]

# Create a Pandas DataFrame
df = pd.DataFrame({
    'StudentID': student_id,
    'Name': names,
    'Age': age,
    'Gender': gender,
    'Grade': grade,
    'Score1': score1,
    'Score2': score2,
    'Score3': score3,
    'City': city,
    'Address': address
})

# Print the DataFrame
df.head()

StudentID              Name  Age  Gender Grade     Score1     Score2  \
0          1       Lohit Golla   20    Male     B  68.485466  62.723625   
1          2   Yamini Yohannan   18    Male     B  70.805411  65.819673   
2          3       Triya Gopal   20  Female     C  79.655417  82.333836   
3          4  Champak Deshmukh   24  Female     B  65.574213  45.543566   
4          5      Samar Thaker   19  Female     A  75.423740  62.523475   

      Score3          City                                   Address  
0  65.119350     Ahmedabad      18 Rastogi Ganj, North Dumdum 322239  
1  74.315888    Gandhidham             842 Gopal Path, Hospet 528518  
2  78.528221  Tiruvottiyur  H.No. 651, Bhakta Marg, Moradabad-011851  
3  72.487622  Secunderabad      H.No. 123 Manne Zila, Gurgaon-791161  
4  74.862938          Agra        935, Yogi Chowk, Vijayawada-435113

In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape to a 2x3 array
reshaped_arr = np.reshape(arr, (2, 3),order='F')

print(reshaped_arr)  # Output: [[1 2 3]
                   #          [4 5 6]]

[[1 3 5]
 [2 4 6]]


In [ ]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.complex64)
zeros = np.zeros_like(arr)
print(zeros)
print('Data Type: ' + str(zeros.dtype))

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
Data Type: complex64



Create an array of ones of given shape

np.ones(): create array of all ones in given shape \
np.ones_like(): create array of all ones with the same shape and data type as the given input array

In [ ]:
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
arr = [[1,2,3], [4,5,6]]
ones = np.ones_like(arr)
print(ones)
print('Data Type: ' + str(ones.dtype))

[[1 1 1]
 [1 1 1]]
Data Type: int64


Create an empty array of given shape

np.empty(): create array of empty values in given shape

np.empty_like(): create array of empty values with the same shape and data type as the given input array

Notice that the initial values are not necessarily set to zeroes.

They are just some garbage values in random memory addresses.

In [ ]:
empty = np.empty((5,5))
print(empty)

[[ 4.00743058e-316  0.00000000e+000  1.24362093e-033  7.71867738e-304
  -2.01346939e-197]
 [-1.99439970e-114  9.82328242e-082  1.96956953e-208  8.97831878e-227
   1.64304299e-265]
 [-8.37524292e-114 -1.16615712e-230  1.41034535e-026  8.97509015e-171
   1.51976236e-091]
 [ 6.81487694e-106 -1.07546223e-172  3.68302919e-304  1.24425812e+268
   3.23611948e-188]
 [ 1.10081394e-289  9.06092918e-312  2.22507386e-307  1.95649823e-316
   6.93788656e-310]]


In [ ]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
empty = np.empty_like(arr)
print(empty)
print('Data Type: ' + str(empty.dtype))

[[1065353216 1073741824 1077936128]
 [1082130432 1084227584 1086324736]]
Data Type: int64


Create an array of constant values of given shape

np.full(): create array of constant values in given shape

np.full_like(): create array of constant values with the same shape and data type as the given input array

In [ ]:
full = np.full((4,4), 5)
print(full)


[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
arr = np.array([[1,2], [3,4]], dtype=np.float64)
full = np.full_like(arr, 5)
print(full)
print('Data Type: ' + str(full.dtype))

[[5. 5.]
 [5. 5.]]
Data Type: float64


Create an array in a repetitive manner \
np.repeat(iterable, reps, axis=None): repeat each element by n times \
iterable: input array \
reps: number of repetitions\
axis: which axis to repeat
along, default is None which will flatten the input array and then repeat
np.tile(): repeat the whole array by n times
iterable: input array
reps: number of repetitions, it can be a tuple to represent repetitions along x-axis and y-axis

In [ ]:
# No axis specified, then flatten the input array first and repeat
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3))

[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [ ]:
# An example of repeating along x-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=0))

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [ ]:
# An example of repeating along y-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=1))

[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]


In [ ]:
# Repeat the whole array by a specified number of times
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [ ]:
# Repeat along specified axes
print(np.tile(arr, (2,2)))

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


###Create an identity matrix of given size

np.eye(size, k=0): create an identity matrix of given size \
size: the size of the identity matrix \
k: the diagonal offset\
np.identity(): same as np.eye() but does not carry parameters

In [ ]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:

# An example of diagonal offset
identity_matrix = np.eye(5, k=-1)
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [ ]:

identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Create an array with given values on the diagonal


In [ ]:
arr = np.random.rand(5,5)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.39106592 0.353825   0.09099307 0.92465065 0.28040603]
 [0.26532197 0.41893426 0.85148129 0.13806684 0.37116812]
 [0.4594456  0.82279367 0.36026414 0.05825279 0.25613669]
 [0.87786486 0.12550069 0.69445054 0.36757315 0.56933979]
 [0.65778642 0.20595904 0.71285681 0.49282037 0.95949298]]
Values on the diagonal: [0.39106592 0.41893426 0.36026414 0.36757315 0.95949298]


In [ ]:
# Not necessarily to be a square matrix
arr = np.random.rand(10,3)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.13165709 0.43783742 0.87964397]
 [0.35180048 0.15918997 0.6635004 ]
 [0.28681795 0.59359901 0.22264161]
 [0.49594462 0.24085257 0.26764839]
 [0.30931607 0.44172183 0.43832435]
 [0.99572881 0.76206396 0.15561091]
 [0.56270279 0.24953673 0.79925299]
 [0.44504887 0.07542262 0.03403838]
 [0.35135974 0.80517607 0.42319845]
 [0.17429636 0.62140564 0.58156008]]
Values on the diagonal: [0.13165709 0.15918997 0.22264161]


In [ ]:
# Create a matrix given values on the diagonal
# All non-diagonal values set to zeros
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


set random state which is independent from the global seed


In [ ]:
rs = np.random.RandomState(321)
rs.rand(10)

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ])


generate a random sample from interval [0, 1) in a given shape

In [ ]:
# generate a random scalar
print(np.random.rand())

0.5699849330879277


In [ ]:
# generate a 1-D array
print(np.random.rand(3))

[0.0101435  0.02510073 0.21741478]


In [ ]:
# generate a 2-D array
print(np.random.rand(3,3))

[[0.75524275 0.03920224 0.18570446]
 [0.50721628 0.92080329 0.52894868]
 [0.95217287 0.49321175 0.04724005]]



generate a sample from the standard normal distribution (mean = 0, var = 1)

In [ ]:
print(np.random.randn(3,3))

[[ 1.33793709 -0.29277249 -0.3342595 ]
 [ 1.20744967  1.38838595 -0.67430609]
 [ 1.35899867 -0.26409987 -0.35140804]]


generate an array of random integers in a given interval [low, high)


In [ ]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i8'))

[2 4 7]


generate an array of random floating-point numbers in the interval [0.0, 1.0)


In [ ]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.78623564 0.12225665 0.62124533 0.69620687 0.44737251 0.8891414
 0.41439759 0.92380641 0.68998013 0.16117871]
[0.35153323 0.89134335 0.8319148  0.04258719 0.45332023 0.73815446
 0.25381082 0.8967563  0.46430358 0.43895692]
[0.78858326 0.39429354 0.44282151 0.35643505 0.46215881 0.99248193
 0.51356675 0.79853416 0.52550416 0.47092887]
[0.16726054 0.27636035 0.35540647 0.4254086  0.77120075 0.04435212
 0.02742692 0.02096286 0.33309364 0.18015601]


generate a random sample from a given 1-D array


In [ ]:

# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.8, 0.1]))

[1 1 0 1 2 1 1 1 1 1]


In [ ]:
print(np.random.choice(3, 10))

[2 1 0 2 1 2 1 1 2 0]


In [ ]:
print(np.random.choice([1,2,3], 10))

[2 2 2 1 2 2 3 1 1 2]


shuffle an array in place


In [ ]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
np.random.shuffle(arr)
print(arr)

[9 0 7 8 6 5 4 3 2 1]


generate a permutation of an array


In [ ]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [1 7 4 5 2 6 9 3 8 0]


#2. Inspect Arrays


In [ ]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)


In [ ]:

print(np.info(arr))

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x4ed14b0
byteorder:  little
byteswap:  False
type: int64
None


inspect the data type of an array


In [ ]:
print(arr.dtype)

int64


inspect the dimension of an array


In [ ]:
print(arr.shape)

(2, 3)


inspect the length of an array


In [ ]:
print(len(arr))

2


inspect the number of elements of an array


In [ ]:
print(arr.size)

6


inspect the no of bytes for every individual of an array


In [ ]:
print(arr.itemsize)

8


inspect the memory size of an array (in byte)


In [ ]:
print(arr.nbytes)

48


inspect the no of  dimensions an array (in byte)


In [ ]:
print(arr.ndim)

2


#4. Math Functions

element-wise addition, subtraction, multiplication and division


In [ ]:
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[11 12 13]
 [14 15 16]]
[[-9 -8 -7]
 [-6 -5 -4]]
[[10 20 30]
 [40 50 60]]
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]


In [ ]:
arr1 = np.array([1,2,3])
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memoryarr = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[1 2 3]
[1 4 9]


element-wise exponentiation


In [ ]:
print(np.exp(arr))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]



element-wise logorithm

In [ ]:

# natural log
print(np.log(arr))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [ ]:
# base 2
print(np.log2(arr))

[[0.         1.         1.5849625 ]
 [2.         2.32192809 2.5849625 ]]


In [ ]:
# base 10
print(np.log10(arr))

[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]
